
version: "3.8"

services:
  secure-frame-iframe:
    build:
      context: .
      dockerfile: js/docker/Dockerfile.demo
      target: secure-frame-iframe
    ports:
      - "8000:8000"
  customer-front-end:
    build:
      context: .
      dockerfile: js/docker/Dockerfile.demo
      target: react-front-end
    ports:
      - "3000:3000"
  customer-back-end:
    build:
      context: .
      dockerfile: js/docker/Dockerfile.demo
      target: demo-back-end
    ports:
      - "3001:3001"
    env_file:
      - .env.dev
#      healthcheck:
#        test: ["CMD-SHELL", "curl http://localhost:3001"]
#        interval: 10s
#        timeout: 5s
#        retries: 5
