version: "3.8"

services:
  integration-test:
    build:
      context: .
      dockerfile: js/docker/demo.dockerfile
      target: integration-test
    entrypoint: npm run test:e2e
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /videos:/repo/js/demo-apps/packages/react-front-end/cypress/videos
    network_mode: host
    depends_on:
      - localstack
      - proxy
      - cdk-init
      - secure-frame-iframe
      - application-front-end
      - application-back-end
      - tokenizerbackend
# Uncomment to open the cypress UI locally
#    environment:
#      - DISPLAY=${DISPLAY}
