header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: by LunaSec (owned by Refinery Labs, Inc)
  paths:
    - '.github/**'
    - 'js/**/*.js'
    - 'js/**/*.jsx'
    - 'js/**/*.ts'
    - 'js/**/*.tsx'
    - 'go/cmd/lunasec/main_cli.go'
    - 'go/**/*.go'
    - 'api-spec/**/*.yaml'
  paths-ignore:
    - '.git'
    - '.idea'
    - '.idea/*'
    - '.idea/**'
    - 'licenses'
    - 'docs'
    - 'docs/**'
    - '**/dist/**'
    - 'js/**/build/**'
    - 'js/sdks/packages/secure-frame-iframe/public/**'
    - 'go/build/**'
    - '**/node_modules/**'
  comment: on-failure

dependency:
  files:
    - '../../../package.json'
    - '../../../js/demo-apps/packages/express-back-end/package.json'
    - '../../../js/demo-apps/packages/react-front-end/package.json'
    - '../../../js/sdks/packages/cli/package.json'
    - '../../../js/sdks/packages/isomorphic-common/package.json'
    - '../../../js/sdks/packages/node-sdk/package.json'
    - '../../../js/sdks/packages/react-sdk/package.json'
    - '../../../js/sdks/packages/secure-frame-iframe/package.json'
    - '../../../js/sdks/packages/tokenizer-sdk/package.json'

