header:
  license:
    spdx-id: CC-BY-SA-4.0
    copyright-owner: LunaSec by Refinery Labs, Inc
  paths:
    - '*.md'
    - '**/*.md'
    - 'docs/*.js*'
    - 'docs/**/*.js*'
    - 'docs/*.ts*'
    - 'docs/**/*.ts*'
    - 'docs/*.md*'
    - 'docs/**/*.md*'
  paths-ignore:
    - 'docs/build/**'
    - 'docs/static/**'
    - 'docs/*.json'
    - 'docs/**/*.json'
    - 'tools/license-checker/skywalking-*/**'
    - '**/node_modules/**'
  comment: on-failure

dependency:
  files:
    - '../../../package.json'
    - '../../../js/demo-apps/packages/express-back-end/package.json'
    - '../../../js/demo-apps/packages/react-front-end/package.json'
    - '../../../js/sdks/packages/cli/package.json'
    - '../../../js/sdks/packages/isomorphic-common/package.json'
    - '../../../js/sdks/packages/node-sdk/package.json'
    - '../../../js/sdks/packages/react-sdk/package.json'
    - '../../../js/sdks/packages/secure-frame-iframe/package.json'
    - '../../../js/sdks/packages/tokenizer-sdk/package.json'

