secure_frame_controller:
  cdn_config:
    protocol: http
    host: ${CDN_HOST}
    main_script: js/main-dev.js
    main_style: main.css
session_controller:
  auth_providers:
    express-back-end:
      url: http://localhost:3001
    graphql-back-end:
      url: http://localhost:3002
