app:
  disable_auth: false
  cors:
    allowed_origins:
      - ${SECURE_FRAME_FRONT_END}
      - ${CUSTOMER_FRONT_END}
    allowed_headers:
      - Authorization
aws_gateway:
  mock: false
  region: us-west-2
  s3_bucket: ${CIPHERTEXT_VAULT_S3_BUCKET}
  table_names:
    metadata: ${METADATA_KV_TABLE}
    keys: ${KEYS_KV_TABLE}
    sessions: ${SESSIONS_KV_TABLE}
session_controller:
  auth_callback_host: ${CUSTOMER_BACK_END}
  auth_callback_path: ${AUTH_CALLBACK_PATH:/secure-frame}
secure_frame_controller:
  views_path: ${SECURE_FRAME_VIEWS_PATH}
  cdn_config: ${SECURE_FRAME_CDN_CONFIG}
tokenizer_controller:
  customer_token_secret: TODO
customer_jwt_verifier:
  # TODO (cthompson) this public key is specifically the customer's public key and the configuration should reflect this
  public_key: ${CUSTOMER_PUBLIC_KEY}