app:
  disable_auth: false
  cors:
    allowed_origins:
      - ${SECURE_FRAME_FRONT_END}
      - ${CUSTOMER_FRONT_END}
    allowed_headers:
      - Authorization
aws_gateway:
  mock: false
  region: us-west-2
  s3_bucket: ${CIPHERTEXT_VAULT_S3_BUCKET}
session_controller:
  auth_callback_url: ${AUTH_CALLBACK_URL}
secure_frame_controller:
  views_path: "${SECURE_FRAME_VIEWS_PATH}"
  cdn_config: ${SECURE_FRAME_CDN_CONFIG}
tokenizer_controller:
  customer_token_secret: ${TOKENIZER_CLIENT_SECRET}
customer_jwt_verifier:
  # TODO (cthompson) this public key is specifically the customer's public key and the configuration should reflect this
  public_key: ${CUSTOMER_PUBLIC_KEY}
jwt_manager:
  signing_keys_arn: ${SIGNING_KEYS_ARN}
hybrid_encryption_manager:
  secure_frame_keyset_arn: ${SECURE_FRAME_KEYSET_ARN}