secure_frame_controller:
  views_path: views/secureframe
  cdn_config:
    protocol: http
    host: ${CDN_HOST}
    main_script: js/main-dev.js
    main_style: main.css
session_controller:
  auth_callback_host: ${CUSTOMER_BACK_END}
tokenizer_controller:
  application_token_secret: test
