
setgrant:
  post:
    tags:
      - Grants
    summary: Create Grant
    operationId: setGrant
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/SetGrantRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/SetGrantResponse'
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
      '500':
        description: An Error Occured
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
verifygrant:
  post:
    tags:
      - Grants
    summary: Verify Grant
    operationId: verifyGrant
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/VerifyGrantRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/VerifyGrantResponse'
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
      '500':
        description: An Error Occured
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
