tokenize:
  post:
    summary: Submit metadata about a token that was uploaded to s3
    operationId: tokenize
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/TokenizeRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/TokenizeResponse'
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'

detokenize:
  post:
    summary: Get an S3 signed download URL for a token
    operationId: detokenize
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/DetokenizeRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/DetokenizeResponse'
      '500':
        description: An Error Occured
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'

      '404':
        description: Unable to locate token
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'