tokenize:
  post:
    tags:
      - Tokens # Added these tags for the documentation generator but then the Tokenizer API generator
      - Default # started splitting up the API based on the tags so added the "Default" tag to everything to rejoin them into one
    summary: Tokenize
    operationId: tokenize
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/TokenizeRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/TokenizeResponse'
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'

detokenize:
  post:
    tags:
      - Tokens
      - Default
    summary: Detokenize
    operationId: detokenize
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './bodies.yaml#/DetokenizeRequest'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/DetokenizeResponse'
      '400':
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'
      '500':
        description: An Error Occured
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'

      '404':
        description: Unable to locate token
        content:
          application/json:
            schema:
              $ref: './bodies.yaml#/ErrorResponse'