project_name: lunasec
before:
  hooks:
    - go mod tidy
builds:
  - id: lunasec-cli
    main: ./cmd/lunasec
    binary: lunasec
    flags:
      - -tags=cli
      - -v
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - arm64
dockers:
  - id: secure-frame
    name_template: lunasec/secure-frame:{{ .Version }}
    dockerfile: ./docker/Dockerfile.secureframe
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{.Version}}-SNAPSHOT-{{.ShortCommit}}'
release:
  name_template: '{{.ProjectName}}-v{{.Version}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
