version: "3.8"

services:
  proxy:
    build:
      dockerfile: ./docker/Dockerfile.httpsproxy
      context: .
    command: -s 4566 -n localstack -t 4566 -c /proxy/proxy.pem -k /proxy/proxy.key
    container_name: localstack_http_proxy
    hostname: localstack-proxy
    depends_on:
      - localstack
    links:
      - localstack
    volumes:
      - "./scripts/proxy/:/proxy"
    ports:
      - "4567:4566"
  #    image: outrigger/https-proxy:1.0
#    container_name: localstack_http_proxy
#    hostname: localstack-proxy
#    depends_on:
#      - localstack
#    links:
#      - localstack
#    labels:
#      com.dnsdock.name: proxy
#      com.dnsdock.image: localstack
#    environment:
#      UPSTREAM_DOMAIN: localstack
#      UPSTREAM_PORT: 4566
#      PROXY_DOMAIN: localstack
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,secretsmanager,sts,cloudformation
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566"]
      interval: 10s
      timeout: 5s
      retries: 5
  cdk-init:
    stdin_open: true
    tty: true
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: docker/Dockerfile.lunasec
    command: --dir /lunasec_local_build deploy --local --build --config-output /config/secureframe/
    volumes:
      - ./config/secureframe/:/config/secureframe/
      - ./lunasec_local_build/:/lunasec_local_build/
    depends_on:
    - localstack
  secureframe:
    env_file:
      - .env.dev
    build:
      args:
        BUILD_TAG: dev
      context: .
      dockerfile: docker/Dockerfile.secureframe
    volumes:
      - ./config/secureframe/:/config/secureframe/
    ports:
      - 37766:37766
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:37766"]
      interval: 10s
      timeout: 5s
      retries: 5
