name: documentation

on:
  pull_request:
    branches: [documentation]
  push:
    branches: [documentation]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Build repo
        run: |
          npx lerna bootstrap
          cd js/sdks && npm run compile:production
      - name: Install Dependencies
        working-directory: docs/
        run: yarn install
      - name: Test Build
        working-directory: docs/
        run: npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Build repo
        run: |
          npx lerna bootstrap
          cd js/sdks && npm run compile:production
      - name: Install Dependencies
        working-directory: docs/
        run: yarn install
      - name: Release to GitHub Pages
        working-directory: docs/
        env:
          DEPLOYMENT_BRANCH: documentation
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "production-services@lunasec.io"
          git config --global user.name "lunasec-production-services"
          npm run deploy