# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm

    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2

    - name: logs
      run: .github/print-docker-logs.sh
      shell: bash

    - id: cache-docker
      uses: actions/cache@v1
      with:
        path: /tmp/docker-registry
        key: lunasec-integration-test-${{ hashFiles('yarn.lock') }}

    - name: Run e2e tests
      # TODO: Exit code from breaks CI currently --exit-code-from
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yaml -f docker-compose.ci.yaml up --build integration-test

#    - name: docker logs
#      if: always()
#      run: docker logs

    - name: docker compose logs
      if: always()
      run: docker-compose logs

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-recording
        path: js/demo-apps/packages/react-front-end/cypress/videos/basic_integration_spec.js.mp4

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: PR Build ${{ github.head_ref }} ${{ job.status }}
        SLACK_COLOR: ${{ job.status }}
