# Copyright 2021 by LunaSec (owned by Refinery Labs, Inc)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: LunaSec Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release to perform (ie. prerelease, patch, minor, major, etc.)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Current Monorepo Version
        run: cat lerna.json | jq -r .version

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: //registry.npmjs.org/:_authToken=${NPM_TOKEN}

      - name: Install License Checker
        working-directory: tools/license-checker/
        run: ./install-skywalking-eyes.sh

      - name: install lerna
        run: npm i -g lerna

      - name: lerna bootstrap
        run: lerna bootstrap

      - name: Configure CI Git User
        run: |
          git config --global user.name 'release-bot'
          git config --global user.email 'release-bot@lunasec.io'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@lunasec:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bump package versions
      - name: create release version
        run: npm run version:release
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}

      # Build all packages
      - name: compile release versions
        run: npm run compile:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      # Fix license headers
#      - name: Fix License Headers
#        run: npm run license:fix
#
#      - name: Update commit
#        run: git commit --amend --no-edit
#
#      # Validate license headers are correct
#      - name: Check License Headers
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: npm run license:check

      # TODO (cthompson) verify that there are no files that have been modified

      # Push all artifacts
      - name: publish release versions
        run: npm run publish:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Push the tagged release version
      - name: push git version tag
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

